import { SiteContentProfile } from "../types";
import { GENERIC_APPLY_CANDIDATE_SELECTORS } from "../common";

export const monsterSiteProfile: SiteContentProfile = {
  key: "monster",
  applyCandidateSelectors: [
    "apply-button-wc",
    "monster-apply-button",
    "[data-testid*='apply' i]",
    "[data-testid='svx_applyButton']",
    "[data-track*='apply' i]",
    "[data-evt*='apply' i]",
    "[data-action*='apply' i]",
    "[data-link*='apply' i]",
    "[data-url*='apply' i]",
    "[aria-label*='apply' i]",
    "[aria-label*='company site' i]",
    "[class*='apply']",
    "button[class*='Apply']",
    "a[class*='Apply']",
    "[class*='applyBtn']",
    "[class*='apply-btn']",
    "[class*='ApplyButton']",
    "[class*='apply-button']",
    "[id*='applyBtn']",
    "[id*='apply-btn']",
    "[data-testid*='Apply']",
    "a[href*='/apply']",
    "a[href*='apply.monster']",
    "a[href*='job-openings'][href*='apply']",
    ...GENERIC_APPLY_CANDIDATE_SELECTORS,
  ],
  currentJobSurfaceSelectors: [
    "[data-testid*='job-detail' i]",
    "[data-testid*='jobDetail' i]",
    "[class*='job-detail']",
    "[class*='jobDetail']",
    "[class*='job-description']",
    "[class*='jobDescription']",
  ],
  resultCollectionMinimum: 25,
  resultCollectionMultiplier: 4,
  resultSurfaceSettleMs: 1000,
};
